--- #YAML:1.0
name:               EBook-EPUB
version:            0.6
abstract:           module for generating EPUB documents
author:
    - Oleksandr Tymoshenko <gonzo@bluezbox.com>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Zip:  0
    Carp:          0
    Data::UUID:    0
    File::Copy:    0
    File::Find:    0
    File::Temp:    0
    Moose:         0.90
    Test::More:    0
    XML::Writer:   0
resources:
    repository:  http://github.com/gonzoua/EBook-EPUB
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
